// ═══════════════════════════════════════════════════════════
// MOCK DATA - Employees Module
// Development uchun mock ma'lumotlar
// ═══════════════════════════════════════════════════════════

import type { Employee, Department, Position, EmployeeStatus, EmploymentType } from '../types'

// ═══════════════════════════════════════════════════════════
// DEPARTMENTS (5 ta)
// ═══════════════════════════════════════════════════════════

export const mockDepartments: Department[] = [
  {
    id: 'dept-it',
    name: "Axborot Texnologiyalari",
    description: "Dasturiy ta'minot va IT infratuzilma",
    managerId: '1',
    employeeCount: 12,
    createdAt: '2024-01-01T00:00:00Z'
  },
  {
    id: 'dept-hr',
    name: "Inson Resurslari",
    description: "Xodimlar bilan ishlash va kadrlar",
    managerId: '5',
    employeeCount: 5,
    createdAt: '2024-01-01T00:00:00Z'
  },
  {
    id: 'dept-finance',
    name: "Moliya",
    description: "Budjet, hisob-kitob va moliyaviy rejalashtirish",
    managerId: '10',
    employeeCount: 8,
    createdAt: '2024-01-01T00:00:00Z'
  },
  {
    id: 'dept-sales',
    name: "Sotuv",
    description: "Mijozlar bilan ishlash va savdo",
    managerId: '13',
    employeeCount: 15,
    createdAt: '2024-01-01T00:00:00Z'
  },
  {
    id: 'dept-marketing',
    name: "Marketing",
    description: "Brend, reklama va raqamli marketing",
    employeeCount: 6,
    createdAt: '2024-01-01T00:00:00Z'
  }
]

// ═══════════════════════════════════════════════════════════
// POSITIONS (10 ta)
// ═══════════════════════════════════════════════════════════

export const mockPositions: Position[] = [
  { id: 'pos-1', name: "Senior Developer", departmentId: 'dept-it', level: 'senior' },
  { id: 'pos-2', name: "HR Manager", departmentId: 'dept-hr', level: 'manager' },
  { id: 'pos-3', name: "Financial Analyst", departmentId: 'dept-finance', level: 'mid' },
  { id: 'pos-4', name: "Sales Representative", departmentId: 'dept-sales', level: 'junior' },
  { id: 'pos-5', name: "Marketing Specialist", departmentId: 'dept-marketing', level: 'mid' },
  { id: 'pos-6', name: "Junior Developer", departmentId: 'dept-it', level: 'junior' },
  { id: 'pos-7', name: "HR Specialist", departmentId: 'dept-hr', level: 'mid' },
  { id: 'pos-8', name: "Lead Developer", departmentId: 'dept-it', level: 'lead' },
  { id: 'pos-9', name: "Sales Manager", departmentId: 'dept-sales', level: 'manager' },
  { id: 'pos-10', name: "Marketing Intern", departmentId: 'dept-marketing', level: 'junior' }
]

// ═══════════════════════════════════════════════════════════
// EMPLOYEES (15 ta o'zbek xodimlar)
// ═══════════════════════════════════════════════════════════

export const mockEmployees: Employee[] = [
  {
    id: '1',
    employeeCode: 'HRM-001',
    firstName: 'Aziz',
    lastName: 'Abdullayev',
    fullName: 'Aziz Abdullayev',
    middleName: 'Rustamovich',
    email: 'aziz.abdullayev@company.uz',
    phone: '+998 90 123 45 67',
    birthDate: '1990-05-15',
    gender: 'male',
    departmentId: 'dept-it',
    positionId: 'pos-8',
    employmentType: 'full_time',
    status: 'active',
    hireDate: '2022-03-10',
    salary: { base: 3000, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2022-03-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: '2',
    employeeCode: 'HRM-002',
    firstName: 'Malika',
    lastName: 'Karimova',
    fullName: 'Malika Karimova',
    middleName: 'Anvarovna',
    email: 'malika.karimova@company.uz',
    phone: '+998 90 234 56 78',
    birthDate: '1988-08-22',
    gender: 'female',
    departmentId: 'dept-hr',
    positionId: 'pos-2',
    employmentType: 'full_time',
    status: 'active',
    hireDate: '2021-06-15',
    salary: { base: 2500, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2021-06-15T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z'
  },
  {
    id: '3',
    employeeCode: 'HRM-003',
    firstName: 'Javohir',
    lastName: 'Sobirov',
    fullName: 'Javohir Sobirov',
    email: 'javohir.sobirov@company.uz',
    phone: '+998 90 345 67 89',
    birthDate: '1995-02-10',
    gender: 'male',
    departmentId: 'dept-it',
    positionId: 'pos-1',
    managerId: '1',
    employmentType: 'full_time',
    status: 'active',
    hireDate: '2023-01-20',
    salary: { base: 2000, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2023-01-20T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z'
  },
  {
    id: '4',
    employeeCode: 'HRM-004',
    firstName: 'Nargiza',
    lastName: 'Usmonova',
    fullName: 'Nargiza Usmonova',
    email: 'nargiza.usmonova@company.uz',
    phone: '+998 90 456 78 90',
    birthDate: '1992-11-05',
    gender: 'female',
    departmentId: 'dept-finance',
    positionId: 'pos-3',
    managerId: '10',
    employmentType: 'full_time',
    status: 'active',
    hireDate: '2022-09-01',
    salary: { base: 1800, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2022-09-01T00:00:00Z',
    updatedAt: '2024-01-02T00:00:00Z'
  },
  {
    id: '5',
    employeeCode: 'HRM-005',
    firstName: 'Dilshod',
    lastName: 'Rahimov',
    fullName: 'Dilshod Rahimov',
    email: 'dilshod.rahimov@company.uz',
    phone: '+998 90 567 89 01',
    birthDate: '1985-04-18',
    gender: 'male',
    departmentId: 'dept-sales',
    positionId: 'pos-9',
    employmentType: 'full_time',
    status: 'active',
    hireDate: '2020-02-15',
    salary: { base: 2800, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2020-02-15T00:00:00Z',
    updatedAt: '2023-12-28T00:00:00Z'
  },
  {
    id: '6',
    employeeCode: 'HRM-006',
    firstName: 'Shahnoza',
    lastName: 'Toshmatova',
    fullName: 'Shahnoza Toshmatova',
    email: 'shahnoza.toshmatova@company.uz',
    phone: '+998 90 678 90 12',
    birthDate: '1998-07-30',
    gender: 'female',
    departmentId: 'dept-marketing',
    positionId: 'pos-10',
    employmentType: 'intern',
    status: 'active',
    hireDate: '2024-01-10',
    salary: { base: 500, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z'
  },
  {
    id: '7',
    employeeCode: 'HRM-007',
    firstName: 'Botir',
    lastName: 'Qodirov',
    fullName: 'Botir Qodirov',
    email: 'botir.qodirov@company.uz',
    phone: '+998 90 789 01 23',
    birthDate: '1993-03-12',
    gender: 'male',
    departmentId: 'dept-it',
    positionId: 'pos-6',
    managerId: '1',
    employmentType: 'full_time',
    status: 'on_leave',
    hireDate: '2023-06-01',
    salary: { base: 1200, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2023-06-01T00:00:00Z',
    updatedAt: '2024-01-20T00:00:00Z'
  },
  {
    id: '8',
    employeeCode: 'HRM-008',
    firstName: 'Gulnora',
    lastName: 'Mamatova',
    fullName: 'Gulnora Mamatova',
    email: 'gulnora.mamatova@company.uz',
    phone: '+998 90 890 12 34',
    birthDate: '1991-09-25',
    gender: 'female',
    departmentId: 'dept-hr',
    positionId: 'pos-7',
    managerId: '2',
    employmentType: 'full_time',
    status: 'active',
    hireDate: '2022-04-18',
    salary: { base: 1500, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2022-04-18T00:00:00Z',
    updatedAt: '2023-11-30T00:00:00Z'
  },
  {
    id: '9',
    employeeCode: 'HRM-009',
    firstName: 'Rustam',
    lastName: 'Aliyev',
    fullName: 'Rustam Aliyev',
    email: 'rustam.aliyev@company.uz',
    phone: '+998 90 901 23 45',
    birthDate: '1987-12-08',
    gender: 'male',
    departmentId: 'dept-sales',
    positionId: 'pos-4',
    managerId: '5',
    employmentType: 'contract',
    status: 'active',
    hireDate: '2023-09-01',
    terminationDate: '2024-09-01',
    salary: { base: 1000, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2023-09-01T00:00:00Z',
    updatedAt: '2023-09-01T00:00:00Z'
  },
  {
    id: '10',
    employeeCode: 'HRM-010',
    firstName: 'Dilnoza',
    lastName: 'Rahmonova',
    fullName: 'Dilnoza Rahmonova',
    email: 'dilnoza.rahmonova@company.uz',
    phone: '+998 90 012 34 56',
    birthDate: '1983-06-14',
    gender: 'female',
    departmentId: 'dept-finance',
    positionId: 'pos-3',
    employmentType: 'full_time',
    status: 'active',
    hireDate: '2019-08-20',
    salary: { base: 2200, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2019-08-20T00:00:00Z',
    updatedAt: '2023-12-15T00:00:00Z'
  },
  {
    id: '11',
    employeeCode: 'HRM-011',
    firstName: 'Anvar',
    lastName: 'Nazarov',
    fullName: 'Anvar Nazarov',
    email: 'anvar.nazarov@company.uz',
    phone: '+998 90 123 45 68',
    birthDate: '1996-01-28',
    gender: 'male',
    departmentId: 'dept-it',
    positionId: 'pos-6',
    managerId: '1',
    employmentType: 'full_time',
    status: 'inactive',
    hireDate: '2023-03-15',
    terminationDate: '2024-01-15',
    salary: { base: 1200, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2023-03-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: '12',
    employeeCode: 'HRM-012',
    firstName: 'Madina',
    lastName: 'Saidova',
    fullName: 'Madina Saidova',
    email: 'madina.saidova@company.uz',
    phone: '+998 90 234 56 79',
    birthDate: '1994-10-03',
    gender: 'female',
    departmentId: 'dept-marketing',
    positionId: 'pos-5',
    managerId: '14',
    employmentType: 'part_time',
    status: 'active',
    hireDate: '2023-07-01',
    salary: { base: 800, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2023-07-01T00:00:00Z',
    updatedAt: '2023-07-01T00:00:00Z'
  },
  {
    id: '13',
    employeeCode: 'HRM-013',
    firstName: 'Farhod',
    lastName: 'Bekmurodov',
    fullName: 'Farhod Bekmurodov',
    email: 'farhod.bekmurodov@company.uz',
    phone: '+998 90 345 67 80',
    birthDate: '1989-05-20',
    gender: 'male',
    departmentId: 'dept-sales',
    positionId: 'pos-4',
    managerId: '5',
    employmentType: 'full_time',
    status: 'terminated',
    hireDate: '2021-11-10',
    terminationDate: '2024-01-10',
    salary: { base: 1500, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2021-11-10T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z'
  },
  {
    id: '14',
    employeeCode: 'HRM-014',
    firstName: 'Lola',
    lastName: 'Hamidova',
    fullName: 'Lola Hamidova',
    email: 'lola.hamidova@company.uz',
    phone: '+998 90 456 78 91',
    birthDate: '1990-02-14',
    gender: 'female',
    departmentId: 'dept-marketing',
    positionId: 'pos-5',
    employmentType: 'full_time',
    status: 'active',
    hireDate: '2020-05-18',
    salary: { base: 2000, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2020-05-18T00:00:00Z',
    updatedAt: '2023-10-25T00:00:00Z'
  },
  {
    id: '15',
    employeeCode: 'HRM-015',
    firstName: 'Sardor',
    lastName: 'Gofurov',
    fullName: 'Sardor Gofurov',
    email: 'sardor.gofurov@company.uz',
    phone: '+998 90 567 89 02',
    birthDate: '1997-08-08',
    gender: 'male',
    departmentId: 'dept-it',
    positionId: 'pos-6',
    managerId: '1',
    employmentType: 'full_time',
    status: 'active',
    hireDate: '2023-11-01',
    salary: { base: 1200, currency: 'USD', paymentType: 'monthly' },
    createdAt: '2023-11-01T00:00:00Z',
    updatedAt: '2023-11-01T00:00:00Z'
  }
]

export default {
  departments: mockDepartments,
  positions: mockPositions,
  employees: mockEmployees
}